/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CrudTable: typeof import('./src/components/Crud-table.vue')['default']
    Loader: typeof import('./src/components/Loader.vue')['default']
  }
}
